name:           menuslider
author:         anutron
#current:       0.1
category:       Interface
tags:           [menu, slide]
docs:           http://clientcide.com/docs/Layout/MenuSlider
demo:           http://www.clientcide.com/wiki/cnet-libraries/08-layout/00.1-menuslider
# requires:
#   - { package: 'some-plugin', version: '0.1' }
#   - { package: 'http://external-plugin.com' }	
